### PR TITLE
Add PWA Support for Web App

### PR DESCRIPTION
**Pull request by MaheshtheDev**
# Add PWA Support for Web App

## Overview
This pull request adds Progressive Web App (PWA) support to the web application. PWAs are web applications that can be installed on a user's device and provide an app-like experience, with features like offline access, push notifications, and home screen shortcuts.

## Changes
- Key Changes:
  - Configured the Next.js application to use the `next-pwa` library for PWA support.
  - Added a `manifest.webmanifest` file in the `public` directory, which defines the PWA's metadata, such as the app name, icons, and theme colors.
  - Configured the `next.config.mjs` file to enable the PWA functionality, with the `next-pwa` plugin.
  - Excluded PWA-related files (e.g., `sw.js`, `workbox-*.js`) from the `.gitignore` file to ensure they are included in the build.
- New Features:
  - The web application can now be installed as a PWA on supported devices, providing an app-like experience for users.
  - Users can add the web app to their home screen and access it quickly, even when offline.
  - The application can receive push notifications, enhancing user engagement and retention.
- Refactoring:
  - No major refactoring was done as part of this change. The changes were focused on adding PWA support to the existing web application.

Overall, this pull request enhances the web application by adding PWA capabilities, improving the user experience and accessibility of the app across different devices and platforms.

> ✨ Generated with love by [Kaizen](https://cloudcode.ai) ❤️

<details>
<summary>Original Description</summary>
None
</details>

### CODE REVIEW

**Comment by CodeTorso** [comment]
try building project locally, next always throws some error in pwa

**Comment by MaheshtheDev** [comment]
@CodeTorso , it worked for me. May i know what kinda error you are facing in local?

**Comment by Dhravya** [comment]
build failed because of frozen lockfile. just do `pnpm i` again and update PR!

**Comment by Dhravya** [comment]
image

**Comment by MaheshtheDev** [comment]
updated the pnpm lock file

**Comment by CodeTorso** [comment]
try deleting it and just doing pnpm install again

**Comment by MaheshtheDev** [comment]
even after doing it, i am not getting any git changes to push

**Pull request merged**
