### PR TITLE
fixed the blur in the add memory card/component

### PR DESCRIPTION
**Pull request by alankritkhatri**
# Fix Blur Effect in Add Memory Card Component

## Overview
This pull request addresses an issue with the blur effect in the "Add Memory Card" component by removing the `backdrop-blur-md` Tailwind CSS class. The changes enhance the visual clarity of the component, improving the user experience.

## Changes
- Key Changes: 
  - Removed the `backdrop-blur-md` class from the `DialogContent` component in both `dialogContentContainer.tsx` and `menu.tsx`.
  
- New Features: 
  - No new features were introduced in this pull request.

- Refactoring: 
  - The code was simplified by eliminating the unnecessary blur effect, which may also contribute to better performance and readability.

> ✨ Generated with love by Kaizen ❤️

<details>
<summary>Original Description</summary>
fixed the blur in the add memory card/component by removing a tailwind class backdrop-blur-md. made changes in dash/dialogContentContainer.tsx anad dash/menu.tsx

adding the before and after. 

BEFORE:
image

AFTER:
image

Please check once before merging
</details>

### CODE REVIEW

**Comment by alankritkhatri** [comment]
BEFORE:

image

AFTER : 
image

**Comment by taylorwaddell** [comment]
Came here to do this. Nice.

**Comment by alankritkhatri** [comment]
feeling stoked my first open source contribution and merged , feels so good man sheeeeeeeeeeeeesh thanks @Dhravya

**Comment by Welding-Torch** [comment]
Thanks for contributing @alankritkhatri 😄😄

**Pull request merged**
